//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieShopApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProdCat = new HashSet<ProdCat>();
            this.ProdOrder = new HashSet<ProdOrder>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string MovieDescription { get; set; }
        public int Price { get; set; }
        public int NrInStore { get; set; }
        public double Rating { get; set; }
        public int ProductTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdCat> ProdCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdOrder> ProdOrder { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
